# Generated by Django 4.1.5 on 2023-01-04 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_rename_description_menu_menu_item_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu_item_description',
            field=models.TextField(default='', max_length=1000, unique=True),
        ),
    ]
