# Generated by Django 4.1.3 on 2023-01-26 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookListDRF', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.DeleteModel(
            name='Bookclass',
        ),
    ]
